openapi: 3.0.1
info:
  title: Example API
  description: Example Description
  version: v1
paths:
  /get/{thing}:
    get:
      tags:
        - demo
      summary: Retrieve single thing
      operationId: getThing
      parameters:
        - name: thing
          in: path
          description: ID of the thing to retrieve
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: Successfully retrieved single thing.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ThingResponse"
      security:
        - BearerAuth: []
        - x-api-key: []
components:
  schemas:
    ThingResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: jwt
    x-api-key:
      type: apiKey
      name: x-api-key
      in: header
